#!/usr/bin/env	bash
## Transfer file `file` to a server
## scp /path/to/file username@a:/path/to/destination
## Handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@44.197.197.123:~/

#If number of arguments is >= 3
if (("$#" < 3))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3""@""$2":~/
fi

