#!/usr/bin/env bash
# Double the number of webservers

apt-get -y update
apt-get -y install nginx
echo "Hello World !" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_404.html
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
udo sed -i "41i \\\terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default

service nginx start
