#!/usr/bin/env bash
# Double the number of webservers
apt-get -y update
apt-get -y install nginx
echo "Hello World !" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
