#!/usr/bin/bash env
# This program install nginx on the container holbertonschoo/265

apt-get update
apt-get install -y nginx
apt-get install curl
service nginx start
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /usr/share/nginx/html/index.html /var/www/html/
