#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize the counter
i=1
# Iterate the loop for 5 times
while [ $i -le 11 ]
    do
    # Print Best school
    echo "Best School"
    # Increment the value of i by 1
    (( i++ ))
done
